/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.Gender".
 */
export type $EnumsGender = "FEMALE" | "MALE" | "OTHER";
/**
 * From https://github.com/sindresorhus/type-fest/
 * Matches any valid JSON value.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "JsonValue".
 */
export type JsonValue =
  | JsonObject
  | {
      length: number;
      "__@unscopables@75": {
        length?: boolean;
        toString?: boolean;
        toLocaleString?: boolean;
        pop?: boolean;
        push?: boolean;
        concat?: boolean;
        join?: boolean;
        reverse?: boolean;
        shift?: boolean;
        slice?: boolean;
        sort?: boolean;
        splice?: boolean;
        unshift?: boolean;
        indexOf?: boolean;
        lastIndexOf?: boolean;
        every?: boolean;
        some?: boolean;
        forEach?: boolean;
        map?: boolean;
        filter?: boolean;
        reduce?: boolean;
        reduceRight?: boolean;
        find?: boolean;
        findIndex?: boolean;
        fill?: boolean;
        copyWithin?: boolean;
        entries?: boolean;
        keys?: boolean;
        values?: boolean;
        includes?: boolean;
        flatMap?: boolean;
        flat?: boolean;
        "__@iterator@73"?: boolean;
        "__@unscopables@75"?: boolean;
        /**
         * Takes an integer value and returns the item at that index,
         * allowing for positive and negative integers.
         * Negative integers count back from the last item in the array.
         */
        at?: boolean;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[0-9]+$".
         */
        [k: string]: boolean;
      };
      [k: string]: JsonValue;
    }
  | (string | number | boolean);
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.BloodGroup".
 */
export type $EnumsBloodGroup = "AB_NEG" | "AB_POS" | "A_NEG" | "A_POS" | "B_NEG" | "B_POS" | "O_NEG" | "O_POS";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "RequestCache".
 */
export type RequestCache = "default" | "force-cache" | "no-cache" | "no-store" | "only-if-cached" | "reload";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "RequestCredentials".
 */
export type RequestCredentials = "include" | "omit" | "same-origin";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "RequestDestination".
 */
export type RequestDestination =
  | ""
  | "audio"
  | "audioworklet"
  | "document"
  | "embed"
  | "font"
  | "frame"
  | "iframe"
  | "image"
  | "manifest"
  | "object"
  | "paintworklet"
  | "report"
  | "script"
  | "sharedworker"
  | "style"
  | "track"
  | "video"
  | "worker"
  | "xslt";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "RequestMode".
 */
export type RequestMode = "cors" | "navigate" | "no-cors" | "same-origin";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "RequestRedirect".
 */
export type RequestRedirect = "error" | "follow" | "manual";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ReferrerPolicy".
 */
export type ReferrerPolicy =
  | ""
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.ParentRole".
 */
export type $EnumsParentRole = "FATHER" | "GUARDIAN" | "MOTHER";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.Day".
 */
export type $EnumsDay = "DEFAULT" | "FRIDAY" | "MONDAY" | "SATURDAY" | "SUNDAY" | "THURSDAY" | "TUESDAY" | "WEDNESDAY";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.MeritalStatus".
 */
export type $EnumsMeritalStatus = "MARRIED" | "NOT_SPECIFIED" | "SEPERATED" | "SINGLE" | "UNMARRIED" | "WIDOWED";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.StaffRole".
 */
export type $EnumsStaffRole =
  | "ADMINISTRATOR"
  | "CAFETERIA_STAFF"
  | "FINANCE_AND_ACCOUNTING_STAFF"
  | "INSTITUTE_COUNSELOR"
  | "INSTITUTE_NURSE"
  | "IT_STAFF"
  | "LIBRARIAN"
  | "MAINTENANCE_STAFF"
  | "MUSIC_COACH"
  | "OTHER"
  | "PRINCIPAL"
  | "SECURITY_GUARD"
  | "SPECIAL_EDUCATION_TEACHER"
  | "SPORTS_COACH"
  | "SUBSTITUTE_TEACHER"
  | "TEACHER"
  | "VICE_PRINCIPAL";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.AttedanceStatus".
 */
export type $EnumsAttedanceStatus = "ABSENT" | "LEAVE" | "PRESENT";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.SubscriptionStatus".
 */
export type $EnumsSubscriptionStatus = "active" | "cancelled" | "pastDue";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "DriverAuthRequest".
 */
export type DriverAuthRequest = Request & {
  user: IdNumberNameStringPasswordStringPhoneStringUsernameStringStatus$Enums;
};
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.VehicleDriverStatus".
 */
export type $EnumsVehicleDriverStatus = "ACTIVE" | "INACTIVE";
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "$Enums.VehicleType".
 */
export type $EnumsVehicleType = "BUS" | "CAR" | "OTHERay" | "VAN";

export interface GeneratedTypes {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Students".
 */
export interface ApiTypesStudents {
  create: {
    res: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums;
    payload: CreateStudentDto;
  };
  findAll: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      students: (ElderSiblingsStudentSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$EnumsBloodGroupRemarksStringHostelIdNumberTransportRouteIdNumberFamilyIdNumberSiblingsStudenElderSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums &
        IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums)[];
    };
    payload: FilterStudentsQueryDto;
  };
  getMockData: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      classes: IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString[];
      students: (
        | {
            rollNumber: string;
            gender: string;
            enrollmentId: {
              [k: string]: unknown;
            };
            dob: string;
            aadhar: string;
            phone: string;
            religion: string;
            caste: {
              [k: string]: unknown;
            };
            photo: string;
            disease: string;
            lastSchool: {
              [k: string]: unknown;
            };
            addressId: {
              [k: string]: unknown;
            };
            firstName: string;
            lastName: string;
            email: {
              [k: string]: unknown;
            };
            enrolled: boolean;
            createdAt: string;
            updatedAt: string;
            studentClassId: {
              [k: string]: unknown;
            };
            sectionId: {
              [k: string]: unknown;
            };
            admissionScheme: {
              [k: string]: unknown;
            };
            subjectStreamId: {
              [k: string]: unknown;
            };
            parents: string;
            section: {
              [k: string]: unknown;
            };
            studentClass: {
              [k: string]: unknown;
            };
            subjectStream: {
              [k: string]: unknown;
            };
          }
        | (ElderSiblingsStudentSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$EnumsBloodGroupRemarksStringHostelIdNumberTransportRouteIdNumberFamilyIdNumberSiblingsStudenElderSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums &
            IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums)
      )[];
    };
    payload: AuthorizedRequestIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber;
  };
  findOne: {
    res: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums;
    payload: number;
  };
  getParents: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: (ParentIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString &
      Relation$Enums)[];
    payload: number;
  };
  createParent: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      message: string;
      data: {
        parent: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString;
        relation: Relation$Enums;
      };
    };
    payload: CreateStudentParentDto;
  };
  updateParent: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      message: string;
      data: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString;
    };
    payload: UpdateStudentParentDto;
  };
  update: {
    res: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums;
    payload: UpdateStudentDto;
  };
  remove: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: number;
  };
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;enrolled:boolean;srn:number;gender:$Enums.Gender;aadhar:string;dob:Date;createdAt:Date;updatedAt:Date;metadata:JsonValue;addressText2:string;city:string;state:string;rfid:string;rollNumber:number;religion:string;category:string;photo:string;lastInstitute:string;grade:number;addressText1:string;postalCode:string;admissionDate:Date;studentClassId:number;sectionId:number;homeGeohash:string;isUsingTransport:boolean;accountNumber:string;bankName:string;branchName:string;ifsc:string;rteScheme:boolean;subjectStreamId:number;bloodGroup:$Enums.BloodGroup;remarks:string;hostelId:number;transportRouteId:number;familyId:number;}".
 */
export interface IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums {
  id: number;
  instituteId: number;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  enrolled: boolean;
  srn: number;
  gender: $EnumsGender;
  aadhar: string;
  dob: string;
  createdAt: string;
  updatedAt: string;
  metadata: JsonValue;
  addressText2: string;
  city: string;
  state: string;
  rfid: string;
  rollNumber: number;
  religion: string;
  category: string;
  photo: string;
  lastInstitute: string;
  grade: number;
  addressText1: string;
  postalCode: string;
  admissionDate: string;
  studentClassId: number;
  sectionId: number;
  homeGeohash: string;
  isUsingTransport: boolean;
  accountNumber: string;
  bankName: string;
  branchName: string;
  ifsc: string;
  rteScheme: boolean;
  subjectStreamId: number;
  bloodGroup: $EnumsBloodGroup;
  remarks: string;
  hostelId: number;
  transportRouteId: number;
  familyId: number;
}
/**
 * From https://github.com/sindresorhus/type-fest/
 * Matches a JSON object.
 * This type can be useful to enforce some input to be JSON-compatible or as a super-type to be extended from.
 */
export interface JsonObject {}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateStudentDto".
 */
export interface CreateStudentDto {
  sectionId?: number;
  subjectStreamId?: number;
  srn: number;
  aadhar: string;
  dob: string;
  firstName: string;
  lastName?: string;
  category?: string;
  email?: string;
  lastSchool?: string;
  gender: $EnumsGender;
  phone: string;
  religion: string;
  rollNumber?: number;
  rteScheme: boolean;
  photo?: string;
  studentClassId?: number;
  addressText1: string;
  addressText2?: string;
  bloodGroup?: $EnumsBloodGroup;
  admissionDate?: string;
  city: string;
  state: string;
  postalCode: string;
  bankName?: string;
  accountNumber?: string;
  branchName?: string;
  ifsc?: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{elderSiblings:{studentSibling:{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;enrolled:boolean;srn:number;gender:$Enums.Gender;aadhar:string;dob:Date;createdAt:Date;updatedAt:Date;metadata:JsonValue;addressText2:string;city:string;state:string;rfid:string;rollNumber:number;religion:string;category:string;photo:string;lastInstitute:string;grade:number;addressText1:string;postalCode:string;admissionDate:Date;studentClassId:number;sectionId:number;homeGeohash:string;isUsingTransport:boolean;accountNumber:string;bankName:string;branchName:string;ifsc:string;rteScheme:boolean;subjectStreamId:number;bloodGroup:$Enums.BloodGroup;remarks:string;hostelId:number;transportRouteId:number;familyId:number;};}[];siblings:{studenElderSibling:{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;enrolled:boolean;srn:number;gender:$Enums.Gender;aadhar:string;dob:Date;createdAt:Date;updatedAt:Date;metadata:JsonValue;addressText2:string;city:string;state:string;rfid:string;rollNumber:number;religion:string;category:string;photo:string;lastInstitute:string;grade:number;addressText1:string;postalCode:string;admissionDate:Date;studentClassId:number;sectionId:number;homeGeohash:string;isUsingTransport:boolean;accountNumber:string;bankName:string;branchName:string;ifsc:string;rteScheme:boolean;subjectStreamId:number;bloodGroup:$Enums.BloodGroup;remarks:string;hostelId:number;transportRouteId:number;familyId:number;};}[];section:{id:number;instituteId:number;title:string;capacity:number;classId:number;};studentClass:{id:number;instituteId:number;createdAt:Date;updatedAt:Date;capacity:number;departmentId:string;classTitle:string;};subjectStream:{id:number;instituteId:number;name:string;studentClassId:number;};}".
 */
export interface ElderSiblingsStudentSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$EnumsBloodGroupRemarksStringHostelIdNumberTransportRouteIdNumberFamilyIdNumberSiblingsStudenElderSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums {
  elderSiblings: StudentSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums[];
  siblings: StudenElderSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums[];
  section: IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber;
  studentClass: IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString;
  subjectStream: IdNumberInstituteIdNumberNameStringStudentClassIdNumber;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{studentSibling:{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;enrolled:boolean;srn:number;gender:$Enums.Gender;aadhar:string;dob:Date;createdAt:Date;updatedAt:Date;metadata:JsonValue;addressText2:string;city:string;state:string;rfid:string;rollNumber:number;religion:string;category:string;photo:string;lastInstitute:string;grade:number;addressText1:string;postalCode:string;admissionDate:Date;studentClassId:number;sectionId:number;homeGeohash:string;isUsingTransport:boolean;accountNumber:string;bankName:string;branchName:string;ifsc:string;rteScheme:boolean;subjectStreamId:number;bloodGroup:$Enums.BloodGroup;remarks:string;hostelId:number;transportRouteId:number;familyId:number;};}".
 */
export interface StudentSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums {
  studentSibling: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{studenElderSibling:{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;enrolled:boolean;srn:number;gender:$Enums.Gender;aadhar:string;dob:Date;createdAt:Date;updatedAt:Date;metadata:JsonValue;addressText2:string;city:string;state:string;rfid:string;rollNumber:number;religion:string;category:string;photo:string;lastInstitute:string;grade:number;addressText1:string;postalCode:string;admissionDate:Date;studentClassId:number;sectionId:number;homeGeohash:string;isUsingTransport:boolean;accountNumber:string;bankName:string;branchName:string;ifsc:string;rteScheme:boolean;subjectStreamId:number;bloodGroup:$Enums.BloodGroup;remarks:string;hostelId:number;transportRouteId:number;familyId:number;};}".
 */
export interface StudenElderSiblingIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums {
  studenElderSibling: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringEnrolledBooleanSrnNumberGender$EnumsGenderAadharStringDobDateCreatedAtDateUpdatedAtDateMetadataJsonValueAddressText2StringCityStringStateStringRfidStringRollNumberNumberReligionStringCategoryStringPhotoStringLastInstituteStringGradeNumberAddressText1StringPostalCodeStringAdmissionDateDateStudentClassIdNumberSectionIdNumberHomeGeohashStringIsUsingTransportBooleanAccountNumberStringBankNameStringBranchNameStringIfscStringRteSchemeBooleanSubjectStreamIdNumberBloodGroup$Enums;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;title:string;capacity:number;classId:number;}".
 */
export interface IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber {
  id: number;
  instituteId: number;
  title: string;
  capacity: number;
  classId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;createdAt:Date;updatedAt:Date;capacity:number;departmentId:string;classTitle:string;}".
 */
export interface IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString {
  id: number;
  instituteId: number;
  createdAt: string;
  updatedAt: string;
  capacity: number;
  departmentId: string;
  classTitle: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;name:string;studentClassId:number;}".
 */
export interface IdNumberInstituteIdNumberNameStringStudentClassIdNumber {
  id: number;
  instituteId: number;
  name: string;
  studentClassId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "FilterStudentsQueryDto".
 */
export interface FilterStudentsQueryDto {
  cursorId?: string;
  limit?: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "AuthorizedRequest<{id:number;instituteId:number;staffUserId:number;readList:boolean;addNew:boolean;attendanceMaster:boolean;attendanceRead:boolean;}|{id:number;instituteId:number;staffUserId:number;readList:boolean;attendanceMaster:boolean;attendanceRead:boolean;update:boolean;delete:boolean;readParents:boolean;manageParents:boolean;admit:boolean;manageClassrooms:boolean;manageTimetable:boolean;readClassrooms:boolean;}|{id:number;instituteId:number;staffUserId:number;}>".
 */
export interface AuthorizedRequestIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber {
  user: AuthorizedStaffUserIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber;
  cache: RequestCache;
  credentials: RequestCredentials;
  destination: RequestDestination;
  headers: Headers;
  integrity: string;
  keepalive: boolean;
  method: string;
  mode: RequestMode;
  redirect: RequestRedirect;
  referrer: string;
  referrerPolicy: ReferrerPolicy;
  signal: AbortSignal;
  url: string;
  body: ReadableStreamUint8Array;
  bodyUsed: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "AuthorizedStaffUser<{id:number;instituteId:number;staffUserId:number;readList:boolean;addNew:boolean;attendanceMaster:boolean;attendanceRead:boolean;}|{id:number;instituteId:number;staffUserId:number;readList:boolean;attendanceMaster:boolean;attendanceRead:boolean;update:boolean;delete:boolean;readParents:boolean;manageParents:boolean;admit:boolean;manageClassrooms:boolean;manageTimetable:boolean;readClassrooms:boolean;}|{id:number;instituteId:number;staffUserId:number;}>".
 */
export interface AuthorizedStaffUserIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber {
  permissions:
    | IdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBoolean
    | IdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBoolean
    | IdNumberInstituteIdNumberStaffUserIdNumber;
  id: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;staffUserId:number;readList:boolean;addNew:boolean;attendanceMaster:boolean;attendanceRead:boolean;}".
 */
export interface IdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBoolean {
  id: number;
  instituteId: number;
  staffUserId: number;
  readList: boolean;
  addNew: boolean;
  attendanceMaster: boolean;
  attendanceRead: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;staffUserId:number;readList:boolean;attendanceMaster:boolean;attendanceRead:boolean;update:boolean;delete:boolean;readParents:boolean;manageParents:boolean;admit:boolean;manageClassrooms:boolean;manageTimetable:boolean;readClassrooms:boolean;}".
 */
export interface IdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBoolean {
  id: number;
  instituteId: number;
  staffUserId: number;
  readList: boolean;
  attendanceMaster: boolean;
  attendanceRead: boolean;
  update: boolean;
  delete: boolean;
  readParents: boolean;
  manageParents: boolean;
  admit: boolean;
  manageClassrooms: boolean;
  manageTimetable: boolean;
  readClassrooms: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;staffUserId:number;}".
 */
export interface IdNumberInstituteIdNumberStaffUserIdNumber {
  id: number;
  instituteId: number;
  staffUserId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "Headers".
 */
export interface Headers {}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "AbortSignal".
 */
export interface AbortSignal {
  aborted: boolean;
  onabort: {};
  reason: unknown;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ReadableStream<Uint8Array>".
 */
export interface ReadableStreamUint8Array {
  locked: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{parent:{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;middleName:string;occupation:string;};}".
 */
export interface ParentIdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString {
  parent: IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;email:string;firstName:string;lastName:string;phone:string;middleName:string;occupation:string;}".
 */
export interface IdNumberInstituteIdNumberEmailStringFirstNameStringLastNameStringPhoneStringMiddleNameStringOccupationString {
  id: number;
  instituteId: number;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  middleName: string;
  occupation: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{relation:$Enums.ParentRole;parentsId:number;studentsId:number;}".
 */
export interface Relation$Enums {
  relation: $EnumsParentRole;
  parentsId: number;
  studentsId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateStudentParentDto".
 */
export interface CreateStudentParentDto {
  email: string;
  firstName: string;
  lastName: string;
  middleName: string;
  occupation: string;
  phone: string;
  relation: $EnumsParentRole;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateStudentParentDto".
 */
export interface UpdateStudentParentDto {
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  middleName?: string;
  occupation?: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateStudentDto".
 */
export interface UpdateStudentDto {
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  gender?: $EnumsGender;
  aadhar?: string;
  dob?: string;
  addressText2?: string;
  city?: string;
  state?: string;
  rollNumber?: number;
  religion?: string;
  category?: string;
  photo?: string;
  addressText1?: string;
  postalCode?: string;
  admissionDate?: string;
  accountNumber?: string;
  bankName?: string;
  branchName?: string;
  ifsc?: string;
  rteScheme?: boolean;
  subjectStreamId?: number;
  bloodGroup?: $EnumsBloodGroup;
  lastSchool?: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.StudentsClasses".
 */
export interface ApiTypesStudentsClasses {
  create: {
    res: IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString;
    payload: unknown;
  };
  getAll: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      classrooms: IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString[];
      sections: IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber[];
    };
    payload: AuthorizedRequestIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber;
  };
  bootstrapStudentClasses: {
    /**
     * Batch Payload for updateMany & deleteMany & createMany
     */
    res: {
      count: number;
    };
    payload: BootstrapClassesDto;
  };
  deleteAll: {
    /**
     * Batch Payload for updateMany & deleteMany & createMany
     */
    res: {
      count: number;
    };
    payload: AuthorizedRequestIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAddNewBooleanAttendanceMasterBooleanAttendanceReadBooleanIdNumberInstituteIdNumberStaffUserIdNumberReadListBooleanAttendanceMasterBooleanAttendanceReadBooleanUpdateBooleanDeleteBooleanReadParentsBooleanManageParentsBooleanAdmitBooleanManageClassroomsBooleanManageTimetableBooleanReadClassroomsBooleanIdNumberInstituteIdNumberStaffUserIdNumber;
  };
  addSection: {
    res: IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber;
    payload: CreateSectionDto;
  };
  getSectionTimetable: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      section: ClassSessionsIdNumberClassTimetableIdNumberSubjectsIdNumberTutorIdNumberStartTimeDateEndTimeDateClassSectionsIdNumberClassIdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleStringClassTimetableIdNumberStartTimeDateEndTimeDateClassSectionsIdNumberDay$Enums &
        IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber;
    };
    payload: number;
  };
  getClassById: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: SubjectsIdNumberStudentClassIdNumberTitleStringIsOptionalBooleanSectionsIdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber &
      IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString;
    payload: unknown;
  };
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "BootstrapClassesDto".
 */
export interface BootstrapClassesDto {
  studentClassSchema: "SENIOR_SECONDARY";
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateSectionDto".
 */
export interface CreateSectionDto {
  classId: number;
  title: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{ClassSessions:{id:number;classTimetableId:number;subjectsId:number;tutorId:number;startTime:Date;endTime:Date;classSectionsId:number;}[];class:{id:number;instituteId:number;createdAt:Date;updatedAt:Date;capacity:number;departmentId:string;classTitle:string;};ClassTimetable:{id:number;startTime:Date;endTime:Date;classSectionsId:number;day:$Enums.Day;}[];}".
 */
export interface ClassSessionsIdNumberClassTimetableIdNumberSubjectsIdNumberTutorIdNumberStartTimeDateEndTimeDateClassSectionsIdNumberClassIdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleStringClassTimetableIdNumberStartTimeDateEndTimeDateClassSectionsIdNumberDay$Enums {
  ClassSessions: IdNumberClassTimetableIdNumberSubjectsIdNumberTutorIdNumberStartTimeDateEndTimeDateClassSectionsIdNumber[];
  class: IdNumberInstituteIdNumberCreatedAtDateUpdatedAtDateCapacityNumberDepartmentIdStringClassTitleString;
  ClassTimetable: IdNumberStartTimeDateEndTimeDateClassSectionsIdNumberDay$Enums[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;classTimetableId:number;subjectsId:number;tutorId:number;startTime:Date;endTime:Date;classSectionsId:number;}".
 */
export interface IdNumberClassTimetableIdNumberSubjectsIdNumberTutorIdNumberStartTimeDateEndTimeDateClassSectionsIdNumber {
  id: number;
  classTimetableId: number;
  subjectsId: number;
  tutorId: number;
  startTime: string;
  endTime: string;
  classSectionsId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;startTime:Date;endTime:Date;classSectionsId:number;day:$Enums.Day;}".
 */
export interface IdNumberStartTimeDateEndTimeDateClassSectionsIdNumberDay$Enums {
  id: number;
  startTime: string;
  endTime: string;
  classSectionsId: number;
  day: $EnumsDay;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{subjects:{id:number;studentClassId:number;title:string;isOptional:boolean;}[];sections:{id:number;instituteId:number;title:string;capacity:number;classId:number;}[];}".
 */
export interface SubjectsIdNumberStudentClassIdNumberTitleStringIsOptionalBooleanSectionsIdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber {
  subjects: IdNumberStudentClassIdNumberTitleStringIsOptionalBoolean[];
  sections: IdNumberInstituteIdNumberTitleStringCapacityNumberClassIdNumber[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;studentClassId:number;title:string;isOptional:boolean;}".
 */
export interface IdNumberStudentClassIdNumberTitleStringIsOptionalBoolean {
  id: number;
  studentClassId: number;
  title: string;
  isOptional: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Institute".
 */
export interface ApiTypesInstitute {
  asyncgetMetaDataByDomainToken: {
    res: IdNumberNameStringLogoString;
    payload: string;
  };
  getMetaDataByToken: {
    res: IdNumberNameStringLogoString_1;
    payload: string;
  };
  create: {
    res: IdNumberNameStringCreatedAtDateUpdatedAtDateAddressTextStringAddressText2StringCityStringStateStringZipCodeStringSubdomainStringPrivateDomainStringPublicIdStringLogoStringStudentAttendanceMasterBooleanStaffAttednanceMasterBoolean;
    payload: CreateInstitueDto;
  };
  findAll: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      name: string;
    };
  };
  findOne: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: string;
  };
  update: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: string;
  };
  remove: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: string;
  };
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;name:string;logo:string;}".
 */
export interface IdNumberNameStringLogoString {
  id: number;
  name: string;
  logo: string;
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;name:string;logo:string;}_1".
 */
export interface IdNumberNameStringLogoString_1 {
  id: number;
  name: string;
  logo: string;
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;name:string;createdAt:Date;updatedAt:Date;addressText:string;addressText2:string;city:string;state:string;zipCode:string;subdomain:string;privateDomain:string;publicId:string;logo:string;studentAttendanceMaster:boolean;staffAttednanceMaster:boolean;}".
 */
export interface IdNumberNameStringCreatedAtDateUpdatedAtDateAddressTextStringAddressText2StringCityStringStateStringZipCodeStringSubdomainStringPrivateDomainStringPublicIdStringLogoStringStudentAttendanceMasterBooleanStaffAttednanceMasterBoolean {
  id: number;
  name: string;
  createdAt: string;
  updatedAt: string;
  addressText: string;
  addressText2: string;
  city: string;
  state: string;
  zipCode: string;
  subdomain: string;
  privateDomain: string;
  publicId: string;
  logo: string;
  studentAttendanceMaster: boolean;
  staffAttednanceMaster: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateInstitueDto".
 */
export interface CreateInstitueDto {
  name: string;
  addressText: string;
  addressText2?: string;
  city: string;
  state: string;
  subdomain: string;
  zipCode: string;
  publicId: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Staff".
 */
export interface ApiTypesStaff {
  getStaffAdminOrThrow: {
    res: IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums;
    payload: number;
  };
  create: {
    res: IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums;
    payload: CreateStaffDto;
  };
  findAll: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums[];
  };
  findOne: {
    res: IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums;
    payload: string;
  };
  fetchStaffAttendance: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      attendance: IdNumberDateDateStaffUsersIdNumberStatus$Enums[];
    };
    payload: number;
  };
  fetchAttendanceByDay: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      attendance: IdNumberDateDateStaffUsersIdNumberStatus$Enums[];
      staff: IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums[];
    };
    payload: FilterStaffAttendanceQuery;
  };
  createAttendance: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      attendance: IdNumberDateDateStaffUsersIdNumberStatus$Enums;
    };
    payload: CreateStaffAttendancePayload;
  };
  saveAttendance: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      /**
       * Batch Payload for updateMany & deleteMany & createMany
       */
      attendance: {
        count: number;
      };
    };
    payload: SaveBulkAttendancePayload;
  };
  fetchStaffUserPermissions: {
    res: UpdateStaffUserPermissions;
    payload: number;
  };
  updatePermissions: {
    res: PartialUpdateStaffUserPermissions;
    payload: UpdateStaffUserPermissions;
  };
  update: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: string;
  };
  remove: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: string;
    payload: string;
  };
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;password:string;email:string;firstName:string;lastName:string;phone:string;username:string;enrolled:boolean;srn:number;picture:string;resume:string;gender:$Enums.Gender;otherDocs:JsonValue[];addressId:number;emergencyContact:string;panNumber:string;salary:number;epfNumber:string;aadhar:string;dateOfJoining:Date;dob:Date;maritalStatus:$Enums.MeritalStatus;role:$Enums.StaffRole;isActive:boolean;createdAt:Date;updatedAt:Date;isTeacher:boolean;metadata:JsonValue;notes:string[];socialLinks:string[];staffAdminJunctionId:number;}".
 */
export interface IdNumberInstituteIdNumberPasswordStringEmailStringFirstNameStringLastNameStringPhoneStringUsernameStringEnrolledBooleanSrnNumberPictureStringResumeStringGender$EnumsGenderOtherDocsJsonValueAddressIdNumberEmergencyContactStringPanNumberStringSalaryNumberEpfNumberStringAadharStringDateOfJoiningDateDobDateMaritalStatus$EnumsMeritalStatusRole$Enums {
  id: number;
  instituteId: number;
  password: string;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  username: string;
  enrolled: boolean;
  srn: number;
  picture: string;
  resume: string;
  gender: $EnumsGender;
  otherDocs: JsonValue[];
  addressId: number;
  emergencyContact: string;
  panNumber: string;
  salary: number;
  epfNumber: string;
  aadhar: string;
  dateOfJoining: string;
  dob: string;
  maritalStatus: $EnumsMeritalStatus;
  role: $EnumsStaffRole;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  isTeacher: boolean;
  metadata: JsonValue;
  notes: string[];
  socialLinks: string[];
  staffAdminJunctionId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateStaffDto".
 */
export interface CreateStaffDto {
  email: string;
  firstName: string;
  lastName: string;
  instituteId: number;
  password: string;
  phone: string;
  role: $EnumsStaffRole;
  username: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;date:Date;staffUsersId:number;status:$Enums.AttedanceStatus;institutesId:number;note:string;}".
 */
export interface IdNumberDateDateStaffUsersIdNumberStatus$Enums {
  id: number;
  date: string;
  staffUsersId: number;
  status: $EnumsAttedanceStatus;
  institutesId: number;
  note: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "FilterStaffAttendanceQuery".
 */
export interface FilterStaffAttendanceQuery {
  date: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateStaffAttendancePayload".
 */
export interface CreateStaffAttendancePayload {
  date: string;
  institutesId: number;
  staffUsersId: number;
  status: $EnumsAttedanceStatus;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "SaveBulkAttendancePayload".
 */
export interface SaveBulkAttendancePayload {
  data: {
    staffUsersId: number;
    status: $EnumsAttedanceStatus;
  }[];
  date: string;
  institutesId: number;
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateStaffUserPermissions".
 */
export interface UpdateStaffUserPermissions {
  studentManagePermissions: UpdateStudentManagePermissions;
  staffManagePermissions: UpdateStaffManagePermissions;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateStudentManagePermissions".
 */
export interface UpdateStudentManagePermissions {
  admit: boolean;
  attendanceMaster: boolean;
  attendanceRead: boolean;
  delete: boolean;
  manageParents: boolean;
  readList: boolean;
  readParents: boolean;
  update: boolean;
  manageClassrooms: boolean;
  manageTimetable: boolean;
  readClassrooms: boolean;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateStaffManagePermissions".
 */
export interface UpdateStaffManagePermissions {
  addNew: boolean;
  attendanceMaster: boolean;
  attendanceRead: boolean;
  readList: boolean;
}
/**
 * The names of exported class must not be frequently changed after usage
 * as it is being used in client side as identifies for types.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "Partial<UpdateStaffUserPermissions>".
 */
export interface PartialUpdateStaffUserPermissions {
  studentManagePermissions?: UpdateStudentManagePermissions;
  staffManagePermissions?: UpdateStaffManagePermissions;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Auth".
 */
export interface ApiTypesAuth {
  signin: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      token: string;
      institute: SubscriptionIdNumberInstituteIdNumberExpiresDateStatus$Enums &
        IdNumberNameStringCreatedAtDateUpdatedAtDateAddressTextStringAddressText2StringCityStringStateStringZipCodeStringSubdomainStringPrivateDomainStringPublicIdStringLogoStringStudentAttendanceMasterBooleanStaffAttednanceMasterBoolean;
      id: number;
      instituteId: number;
      password: string;
      email: string;
      firstName: string;
      lastName: string;
      phone: string;
      username: string;
      enrolled: boolean;
      srn: number;
      picture: string;
      resume: string;
      gender: $EnumsGender;
      otherDocs: JsonValue[];
      addressId: number;
      emergencyContact: string;
      panNumber: string;
      salary: number;
      epfNumber: string;
      aadhar: string;
      dateOfJoining: string;
      dob: string;
      maritalStatus: $EnumsMeritalStatus;
      role: $EnumsStaffRole;
      isActive: boolean;
      createdAt: string;
      updatedAt: string;
      isTeacher: boolean;
      metadata: JsonValue;
      notes: string[];
      socialLinks: string[];
      staffAdminJunctionId: number;
    };
    payload: SignInDto;
  };
  signinAdmin: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      token: string;
      permissions: IdNumberAdminIdNumber;
      id: number;
      password: string;
      email: string;
      firstName: string;
      lastName: string;
      phone: string;
      username: string;
    };
    payload: SignInDto;
  };
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{Subscription:{id:number;instituteId:number;expires:Date;status:$Enums.SubscriptionStatus;startDate:Date;endDate:Date;paymentMethod:string;price:Decimal;}[];}".
 */
export interface SubscriptionIdNumberInstituteIdNumberExpiresDateStatus$Enums {
  Subscription: IdNumberInstituteIdNumberExpiresDateStatus$Enums[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;instituteId:number;expires:Date;status:$Enums.SubscriptionStatus;startDate:Date;endDate:Date;paymentMethod:string;price:Decimal;}".
 */
export interface IdNumberInstituteIdNumberExpiresDateStatus$Enums {
  id: number;
  instituteId: number;
  expires: string;
  status: $EnumsSubscriptionStatus;
  startDate: string;
  endDate: string;
  paymentMethod: string;
  price: Decimal;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "Decimal".
 */
export interface Decimal {
  d: number[];
  e: number;
  s: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "SignInDto".
 */
export interface SignInDto {
  identifierType?: "EMAIL" | "USERNAME";
  identifier: string;
  password: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;adminId:number;}".
 */
export interface IdNumberAdminIdNumber {
  id: number;
  adminId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Driver".
 */
export interface ApiTypesDriver {
  loadRoutes: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      routes: IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber[];
      trips: IdNumberDateDateIsActiveBooleanTransportRouteIdNumberInstitutesIdNumberTransportVehiclesIdNumberTripStartTimeDateTripEndTimeDateVehicleDriverIdNumberTripPathString[];
    };
    payload: DriverAuthRequest;
  };
  loadActiveTripMetadata: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: RouteStudentsFirstNameStringLastNameStringStudentClassIdNumberHomeGeohashStringStoppagesTitleStringGeohashStringOrderNumNumberIdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber &
      IdNumberDateDateIsActiveBooleanTransportRouteIdNumberInstitutesIdNumberTransportVehiclesIdNumberTripStartTimeDateTripEndTimeDateVehicleDriverIdNumberTripPathString;
    payload: DriverAuthRequest;
  };
  initiateTrip: {
    res: IdNumberDateDateIsActiveBooleanTransportRouteIdNumberInstitutesIdNumberTransportVehiclesIdNumberTripStartTimeDateTripEndTimeDateVehicleDriverIdNumberTripPathString;
    payload: CreateTripDto;
  };
  endTrip: {
    res: IdNumberDateDateIsActiveBooleanTransportRouteIdNumberInstitutesIdNumberTransportVehiclesIdNumberTripStartTimeDateTripEndTimeDateVehicleDriverIdNumberTripPathString;
    payload: EndTripDto;
  };
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;title:string;institutesId:number;transportVehiclesId:number;studentCount:number;}".
 */
export interface IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber {
  id: number;
  title: string;
  institutesId: number;
  transportVehiclesId: number;
  studentCount: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;date:Date;isActive:boolean;transportRouteId:number;institutesId:number;transportVehiclesId:number;tripStartTime:Date;tripEndTime:Date;vehicleDriverId:number;tripPath:string;}".
 */
export interface IdNumberDateDateIsActiveBooleanTransportRouteIdNumberInstitutesIdNumberTransportVehiclesIdNumberTripStartTimeDateTripEndTimeDateVehicleDriverIdNumberTripPathString {
  id: number;
  date: string;
  isActive: boolean;
  transportRouteId: number;
  institutesId: number;
  transportVehiclesId: number;
  tripStartTime: string;
  tripEndTime: string;
  vehicleDriverId: number;
  tripPath: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "Request".
 */
export interface Request {
  cache: RequestCache;
  credentials: RequestCredentials;
  destination: RequestDestination;
  headers: Headers;
  integrity: string;
  keepalive: boolean;
  method: string;
  mode: RequestMode;
  redirect: RequestRedirect;
  referrer: string;
  referrerPolicy: ReferrerPolicy;
  signal: AbortSignal;
  url: string;
  body: ReadableStreamUint8Array;
  bodyUsed: boolean;
}
/**
 * Model VehicleDriver
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;name:string;password:string;phone:string;username:string;status:$Enums.VehicleDriverStatus;createdAt:Date;updatedAt:Date;licenseNumber:string;institutesId:number;}".
 */
export interface IdNumberNameStringPasswordStringPhoneStringUsernameStringStatus$Enums {
  id: number;
  name: string;
  password: string;
  phone: string;
  username: string;
  status: $EnumsVehicleDriverStatus;
  createdAt: string;
  updatedAt: string;
  licenseNumber: string;
  institutesId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{route:{Students:{firstName:string;lastName:string;studentClassId:number;homeGeohash:string;}[];Stoppages:{title:string;geohash:string;orderNum:number;}[];}&{id:number;title:string;institutesId:number;transportVehiclesId:number;studentCount:number;};}".
 */
export interface RouteStudentsFirstNameStringLastNameStringStudentClassIdNumberHomeGeohashStringStoppagesTitleStringGeohashStringOrderNumNumberIdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber {
  route: StudentsFirstNameStringLastNameStringStudentClassIdNumberHomeGeohashStringStoppagesTitleStringGeohashStringOrderNumNumber &
    IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{Students:{firstName:string;lastName:string;studentClassId:number;homeGeohash:string;}[];Stoppages:{title:string;geohash:string;orderNum:number;}[];}".
 */
export interface StudentsFirstNameStringLastNameStringStudentClassIdNumberHomeGeohashStringStoppagesTitleStringGeohashStringOrderNumNumber {
  Students: FirstNameStringLastNameStringStudentClassIdNumberHomeGeohashString[];
  Stoppages: TitleStringGeohashStringOrderNumNumber[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{firstName:string;lastName:string;studentClassId:number;homeGeohash:string;}".
 */
export interface FirstNameStringLastNameStringStudentClassIdNumberHomeGeohashString {
  firstName: string;
  lastName: string;
  studentClassId: number;
  homeGeohash: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{title:string;geohash:string;orderNum:number;}".
 */
export interface TitleStringGeohashStringOrderNumNumber {
  title: string;
  geohash: string;
  orderNum: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateTripDto".
 */
export interface CreateTripDto {
  transportRouteId: number;
  transportVehiclesId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "EndTripDto".
 */
export interface EndTripDto {}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "ApiTypes.Transport".
 */
export interface ApiTypesTransport {
  fetchRoutes: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber[];
  };
  fetchRouteById: {
    res: IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber;
    payload: number;
  };
  createRoute: {
    res: IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber;
    payload: CreateRouteDto;
  };
  addStudentToRoute: {
    /**
     * Batch Payload for updateMany & deleteMany & createMany
     */
    res: {
      count: number;
    };
    payload: AddStudentToRouteDto;
  };
  updateRoute: {
    res: IdNumberTitleStringInstitutesIdNumberTransportVehiclesIdNumberStudentCountNumber;
    payload: CreateRouteDto;
  };
  createOrUpdateStoppage: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: {
      updated: IdNumberTransportRouteIdNumberTitleStringGeohashStringOrderNumNumber[];
      created: PrismaPrismaPromisePrisma;
    };
    payload: AddRouteDto;
  };
  deleteStoppage: {
    res: IdNumberTransportRouteIdNumberTitleStringGeohashStringOrderNumNumber;
    payload: number;
  };
  fetchDrivers: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: IdNumberNameStringPasswordStringPhoneStringUsernameStringStatus$Enums[];
  };
  createDriver: {
    res: IdNumberNameStringPasswordStringPhoneStringUsernameStringStatus$Enums;
    payload: unknown;
  };
  fetchVehicles: {
    /**
     * The names of exported class must not be frequently changed after usage
     * as it is being used in client side as identifies for types.
     */
    res: IdNumberCreatedAtDateUpdatedAtDateType$Enums[];
  };
  createVehicle: {
    res: IdNumberCreatedAtDateUpdatedAtDateType$Enums;
    payload: CreateVehicleDto;
  };
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateRouteDto".
 */
export interface CreateRouteDto {
  id: number;
  institutesId: number;
  title: string;
  studentCount: number;
  transportVehiclesId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "AddStudentToRouteDto".
 */
export interface AddStudentToRouteDto {
  routeId: number;
  studentIds: number[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;transportRouteId:number;title:string;geohash:string;orderNum:number;}".
 */
export interface IdNumberTransportRouteIdNumberTitleStringGeohashStringOrderNumNumber {
  id: number;
  transportRouteId: number;
  title: string;
  geohash: string;
  orderNum: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "Prisma.PrismaPromise<Prisma.BatchPayload>".
 */
export interface PrismaPrismaPromisePrisma {
  "__@toStringTag@3743": "PrismaPromise";
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "AddRouteDto".
 */
export interface AddRouteDto {
  routeId: number;
  newStoppages: StoppageDto[];
  updateStoppages: UpdaeStoppageProp[];
  deletedStoppages: number[];
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "StoppageDto".
 */
export interface StoppageDto {
  geohash: string;
  orderNum: number;
  title: string;
  transportRouteId: number;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdaeStoppageProp".
 */
export interface UpdaeStoppageProp {
  id: number;
  data: UpdateAccountDto;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "UpdateAccountDto".
 */
export interface UpdateAccountDto {}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "{id:number;createdAt:Date;updatedAt:Date;type:$Enums.VehicleType;capacity:number;institutesId:number;registrationNumber:string;model:string;}".
 */
export interface IdNumberCreatedAtDateUpdatedAtDateType$Enums {
  id: number;
  createdAt: string;
  updatedAt: string;
  type: $EnumsVehicleType;
  capacity: number;
  institutesId: number;
  registrationNumber: string;
  model: string;
}
/**
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "CreateVehicleDto".
 */
export interface CreateVehicleDto {
  capacity: number;
  createdAt: string;
  id: number;
  institutesId: number;
  updatedAt: string;
  model: string;
  registrationNumber: string;
  type: $EnumsVehicleType;
}
/**
 * From https://github.com/sindresorhus/type-fest/
 * Matches a JSON object.
 * This type can be useful to enforce some input to be JSON-compatible or as a super-type to be extended from.
 *
 * This interface was referenced by `GeneratedTypes`'s JSON-Schema
 * via the `definition` "JsonObject".
 */
export interface JsonObject1 {}
